### ISSUE TITLE
Work perfect on Chrome but error on Safari

### ISSUE THREAD

**Issue by drducmanh** [namnh240795/number-to-text-vietnamese#12]
Safari 15.4 show console log: SyntaxError: Invalid regular expression: invalid group specifier name (anonymous function) —index.js:1
and doesn't work on safari of iphone too.
Please fix it!

**Comment by namnh240795** [comment]
I've tested it on safari and it work fine.
This is not related to the library, next time please provide a repository to reproduce the bug.
